/* Generated by AN DISI Unibo */ 
package it.unibo.oprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Oprobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var OWNER = "$name"  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://broker.hivemq.com" )
						CommUtils.outgreen("$name STARTS")
						//val m = MsgUtil.buildEvent(name, "mqtt_info", "start" ) 
						publish(MsgUtil.buildEvent(name,"mqtt_info","start").toString(), "it.unib0.iss.waste-incinerator-service" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engage", cond=doswitch() )
				}	 
				state("engage") { //this:State
					action { //it:State
						CommUtils.outgreen("$name request engage")
						request("engage", "engage($OWNER,350)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="inHome",cond=whenReply("engagedone"))
					transition(edgeName="t011",targetState="handleEngageRefused",cond=whenReply("engagerefused"))
				}	 
				state("handleEngageRefused") { //this:State
					action { //it:State
						CommUtils.outblack("engage $name refused, re-trying after some delay..")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engage", cond=doswitch() )
				}	 
				state("execGoHome") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("gohome(TARGETX,TARGETY)"), Term.createTerm("gohome(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								        var X = payloadArg(0).toInt()
								        var Y = payloadArg(1).toInt()
								CommUtils.outgreen("$name - Moving to ($X,$Y)")
								delay(500) 
								request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="inHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t013",targetState="execGoHome",cond=whenReply("moverobotfailed"))
				}	 
				state("inHome") { //this:State
					action { //it:State
						CommUtils.outgreen("$name - waiting in home...")
						answer("gohome", "gohome_status", "gohome_status(0)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="execGetRp",cond=whenRequest("getrp"))
					transition(edgeName="t015",targetState="execExtractAsh",cond=whenRequest("extractash"))
				}	 
				state("execGetRp") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("getrp(TARGETX,TARGETY)"), Term.createTerm("getrp(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								        var X = payloadArg(0).toInt()
								        var Y = payloadArg(1).toInt()
								CommUtils.outgreen("$name - Moving to ($X,$Y)")
								delay(500) 
								//val m = MsgUtil.buildEvent(name, "mqtt_info", "moving_to_WasteIn_port" ) 
								publish(MsgUtil.buildEvent(name,"mqtt_info","moving_to_WasteIn_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
								request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="getRpOk",cond=whenReply("moverobotdone"))
					transition(edgeName="t017",targetState="execGetRp",cond=whenReply("moverobotfailed"))
				}	 
				state("getRpOk") { //this:State
					action { //it:State
						//val m = MsgUtil.buildEvent(name, "mqtt_info", "collected_RP_from_WasteIn_port" ) 
						publish(MsgUtil.buildEvent(name,"mqtt_info","collected_RP_from_WasteIn_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
						delay(200) 
						forward("unload_weight", "unload_weight(50)" ,"scale_device" ) 
						answer("getrp", "getrp_status", "getrp_status(0)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t118",targetState="execDepositRp",cond=whenRequest("depositrp"))
				}	 
				state("execDepositRp") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("depositrp(TARGETX,TARGETY)"), Term.createTerm("depositrp(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								        var X = payloadArg(0).toInt()
								        var Y = payloadArg(1).toInt()
								CommUtils.outgreen("$name - Depositing RP in ($X, $Y)")
								delay(500) 
								//val m = MsgUtil.buildEvent(name, "mqtt_info", "moving_to_BurnIn_port" ) 
								publish(MsgUtil.buildEvent(name,"mqtt_info","moving_to_BurnIn_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
								request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t219",targetState="depositRpOk",cond=whenReply("moverobotdone"))
					transition(edgeName="t220",targetState="execDepositRp",cond=whenReply("moverobotfailed"))
				}	 
				state("depositRpOk") { //this:State
					action { //it:State
						//val m = MsgUtil.buildEvent(name, "mqtt_info", "deposited_RP_in_BurnIn_port" ) 
						publish(MsgUtil.buildEvent(name,"mqtt_info","deposited_RP_in_BurnIn_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
						answer("depositrp", "depositrp_status", "depositrp_status(0)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t321",targetState="execGoHome",cond=whenRequest("gohome"))
				}	 
				state("execExtractAsh") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("extractash(TARGETX,TARGETY)"), Term.createTerm("extractash(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								        var X = payloadArg(0).toInt()
								        var Y = payloadArg(1).toInt()
								CommUtils.outgreen("$name - Moving to ($X,$Y)")
								delay(500) 
								//val m = MsgUtil.buildEvent(name, "mqtt_info", "moving_to_BurnOut_port" ) 
								publish(MsgUtil.buildEvent(name,"mqtt_info","moving_to_BurnOut_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
								request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t022",targetState="extractAshOk",cond=whenReply("moverobotdone"))
					transition(edgeName="t023",targetState="execExtractAsh",cond=whenReply("moverobotfailed"))
				}	 
				state("extractAshOk") { //this:State
					action { //it:State
						//val m = MsgUtil.buildEvent(name, "mqtt_info", "collected_ash_from_BurnOut_port" ) 
						publish(MsgUtil.buildEvent(name,"mqtt_info","collected_ash_from_BurnOut_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
						answer("extractash", "extractash_status", "extractash_status(0)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="execDepositAsh",cond=whenRequest("depositash"))
				}	 
				state("execDepositAsh") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("depositash(TARGETX,TARGETY)"), Term.createTerm("depositash(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								        var X = payloadArg(0).toInt()
								        var Y = payloadArg(1).toInt()
								CommUtils.outgreen("$name - Depositing Ash in ($X, $Y)")
								delay(500) 
								//val m = MsgUtil.buildEvent(name, "mqtt_info", "moving_to_AshOut_port" ) 
								publish(MsgUtil.buildEvent(name,"mqtt_info","moving_to_AshOut_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
								request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t025",targetState="depositAshOk",cond=whenReply("moverobotdone"))
					transition(edgeName="t026",targetState="execDepositAsh",cond=whenReply("moverobotfailed"))
				}	 
				state("depositAshOk") { //this:State
					action { //it:State
						//val m = MsgUtil.buildEvent(name, "mqtt_info", "deposited_ash_in_AshOut_port" ) 
						publish(MsgUtil.buildEvent(name,"mqtt_info","deposited_ash_in_AshOut_port").toString(), "it.unib0.iss.waste-incinerator-service" )   
						forward("load_ash", "load_ash(25)" ,"sonar_device" ) 
						answer("depositash", "depositash_status", "depositash_status(0)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t027",targetState="execGoHome",cond=whenRequest("gohome"))
				}	 
			}
		}
} 
